// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackHub.Geofencing.Infrastructure.ManagerDB;

#nullable disable

namespace TrackHub.Geofencing.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260717195858_GeofenceAlertsCirclesAndEventAccountId")]
    partial class GeofenceAlertsCirclesAndEventAccountId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.AccountFeature", b =>
                {
                    b.Property<Guid>("AccountFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectivefrom");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectiveto");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("featurekey");

                    b.HasKey("AccountFeatureId");

                    b.HasIndex("AccountId", "FeatureKey");

                    b.ToTable("account_features", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actorid");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actortype");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlationid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("newvaluesjson");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredat");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("oldvaluesjson");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourcetype");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("useragent");

                    b.HasKey("AuditEventId");

                    b.ToTable("audit_events", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.Geofence", b =>
                {
                    b.Property<Guid>("GeofenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("AlertOnEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alertonentry");

                    b.Property<bool>("AlertOnExit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("alertonexit");

                    b.Property<Point>("CircleCenter")
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("circlecenter");

                    b.Property<double?>("CircleRadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("circleradiusmeters");

                    b.Property<short>("Color")
                        .HasColumnType("smallint")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("DwellThresholdMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("dwellthresholdminutes");

                    b.Property<Polygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (Polygon, 4326)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("GeofenceId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_geofences_accountid");

                    b.HasIndex("Geom")
                        .HasDatabaseName("geofence_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("geofences", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.GeofenceEvent", b =>
                {
                    b.Property<Guid>("GeofenceEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset?>("DepartureTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departuretimestamp");

                    b.Property<DateTimeOffset?>("DwellAlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dwellalertedat");

                    b.Property<DateTimeOffset>("EventDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<Guid>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofenceid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("GeofenceEventId");

                    b.HasIndex("GeofenceId")
                        .HasDatabaseName("ix_geofenceevent_geofenceid");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_geofenceevent_transporterid");

                    b.HasIndex("AccountId", "EventDateTime")
                        .HasDatabaseName("ix_geofenceevent_accountid_datetime");

                    b.HasIndex("TransporterId", "GeofenceId", "DepartureTimestamp")
                        .HasDatabaseName("ix_geofenceevent_open_events")
                        .HasFilter("departuretimestamp IS NULL");

                    b.ToTable("geofenceevents", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.VwTransporterPosition", b =>
                {
                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("TransporterId");

                    b.ToTable((string)null);

                    b.ToView("vw_transporter_position", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.VwUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_users", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.GeofenceEvent", b =>
                {
                    b.HasOne("TrackHub.Geofencing.Infrastructure.ManagerDB.Entities.Geofence", "Geofence")
                        .WithMany()
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Geofence");
                });
#pragma warning restore 612, 618
        }
    }
}
