// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackHub.Manager.Infrastructure.ManagerDB;

#nullable disable

namespace TrackHub.Manager.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.ManagerDB.Entities.Geofence", b =>
                {
                    b.Property<Guid>("GeofenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<short>("Color")
                        .HasColumnType("smallint")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Polygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (Polygon, 4326)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("GeofenceId");

                    b.HasIndex("Geom")
                        .HasDatabaseName("geofence_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("geofences", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.ManagerDB.Entities.GeofenceEvent", b =>
                {
                    b.Property<Guid>("GeofenceEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<TimeSpan?>("DepartureOffset")
                        .HasColumnType("interval")
                        .HasColumnName("departureoffset");

                    b.Property<DateTime?>("DepartureTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departuretimestamp");

                    b.Property<Guid>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofenceid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<TimeSpan>("Offset")
                        .HasColumnType("interval")
                        .HasColumnName("offset");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("GeofenceEventId");

                    b.HasIndex("GeofenceId")
                        .HasDatabaseName("ix_geofenceevent_geofenceid");

                    b.HasIndex("TransporterId")
                        .HasDatabaseName("ix_geofenceevent_transporterid");

                    b.HasIndex("TransporterId", "GeofenceId", "DepartureTimestamp")
                        .HasDatabaseName("ix_geofenceevent_open_events")
                        .HasFilter("departuretimestamp IS NULL");

                    b.ToTable("geofenceevents", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.ManagerDB.Entities.VwTransporterPosition", b =>
                {
                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("TransporterId");

                    b.ToTable((string)null);

                    b.ToView("vw_transporter_position", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.ManagerDB.Entities.VwUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_users", "geofencing");
                });

            modelBuilder.Entity("TrackHub.Manager.Infrastructure.ManagerDB.Entities.GeofenceEvent", b =>
                {
                    b.HasOne("TrackHub.Manager.Infrastructure.ManagerDB.Entities.Geofence", "Geofence")
                        .WithMany()
                        .HasForeignKey("GeofenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Geofence");
                });
#pragma warning restore 612, 618
        }
    }
}
